### ISSUE TITLE
Предложения по переработке

### ISSUE THREAD

**Issue by KernelMrex** [KernelMrex/RainbowSlides#1]
Думаю следует переименовать `Pointers` в `Position`
https://github.com/KernelMrex/RainbowSlides/blob/0759d316faf95662a8d74583c03d2a9e293a91df/src/types.ts#L74-L77

Не думаю что стоит убрать этот тип. И просто оставить поля в типе
https://github.com/KernelMrex/RainbowSlides/blob/0759d316faf95662a8d74583c03d2a9e293a91df/src/types.ts#L69-L72

Вот эта штука выглядит ненужной, так как у нас уже есть это в самих типах
https://github.com/KernelMrex/RainbowSlides/blob/0759d316faf95662a8d74583c03d2a9e293a91df/src/types.ts#L61

Возможно не самый оптимальный метод хранения полностью дерева состояния
https://github.com/KernelMrex/RainbowSlides/blob/0759d316faf95662a8d74583c03d2a9e293a91df/src/types.ts#L24-L26

Название содержит в себе излишние описание. Думаю стоит подумать над сменой названия
https://github.com/KernelMrex/RainbowSlides/blob/0759d316faf95662a8d74583c03d2a9e293a91df/src/types.ts#L28

Тут тоже слишком сильная декомпозиция. Банально может быть ситуация 
https://github.com/KernelMrex/RainbowSlides/blob/0759d316faf95662a8d74583c03d2a9e293a91df/src/types.ts#L63-L67

Пока хватит. Может быть ещё докину :)

**Comment by Andreanapolicy** [comment]
Ты не дописал последнюю правку. Все изменения сделаю и залью как только будет время)

**Comment by KernelMrex** [comment]
Fixed
